apiVersion: v1
kind: Service
metadata:
  name: mypythonapp
  namespace: mypythonapp
spec:
  type: NodePort
  selector:
    app: mypythonapp
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 5000
    nodePort: 30007
