apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: {{ .Values.jfrog.auth.secret_token }}

metadata:
  name: {{ .Values.appname}}-secret
  namespace: {{ .Values.appname}}
type: kubernetes.io/dockerconfigjson
