pipeline{
    tools { 
        maven 'maven' 
        jdk 'jdk17' 
    }    
    agent any
    stages {
        
        stage('Git Clone') {
            steps{
                git credentialsId: 'ec2-jenkins-private-key', 
                url: 'git@github.com:divyar28/Terraform-ansible-provision-bootstrap-repo.git'
             }
        }
        
        stage('Terraform'){
            steps{
            
               dir("ANSIBLE-JENKINS"){

                    sh '''
                        ls -ltr
                    '''
               }
            }
        }
        
        stage('Maven Build'){
            steps{
            
               dir("my-java-app"){
		// the below gets directly executed on the jenkins server filesystem
                //sh 'mvn package -DskipTests'
		
		// the below commands builds a my-java-app's docker container and NOT within
		// Jenkins filesystem
		 sh 'docker buildx build .'

               }
            }
        }        
    }
}
