---
- hosts: target
  become: yes
  remote_user: ec2-user
  become_user: root
  
  tasks:
   - name: terraform install
     unarchive:
       src: https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip
       dest: /usr/bin
       remote_src: True
