(base) sharsha@C02C41X1MD6N gatling % cat values.yaml 
name: ""
namespace: gatling

nameOverride: ""
fullnameOverride: ""

extraLabels: {}
resources: {}

backoffLimit: 1
parallelism: 1
completions: 1

image:
  repository: discovery-wbd-streaming-virtual-docker.jfrog.io/loadtest-gatling
  tag: 0.0.1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred
  - name: artifactory-da-reader-token
