name: myjavaapp
namespace: myjavaapp

nameOverride: ""
fullnameOverride: ""

extraLabels: {}
resources: {}

backoffLimit: 1
parallelism: 1
completions: 1

image:
  repository: test1919.jfrog.io
  repository_path: docker/hello-world
  tag: 0.0.1
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred
  - name: artifactory-da-reader-token
