# This is a basic workflow to help you get started with Actions

name: gha basic

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -ltr
          pwd

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Build with Maven
#        working-directory: ./my-java-app
#        run: mvn package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to Jfrog
        uses: docker/login-action@v1
        with:
          registry: test1919.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: test1919.jfrog.io/myjavaappdocker/hello-world:3.0.0
          file: my-java-app/Dockerfile
          context: my-java-app

#     - name: Docker build
#        uses: docker/build-push-action@v4
#        with:
#          file: my-java-app/Dockerfile
#          context: my-java-app

     # setup Helm
#       - name: Setup Helm
#        uses: azure/setup-helm@b5b231a831f96336bbfeccc1329990f0005c5bb1
 #        with:
  #         version: 'v3.10.1'
